version: '3'

services:
  app:
    build: .
    ports:
      - ${API_PORT}:${API_PORT}
    depends_on:
      - redis
    restart: always

  redis:
    image: "redis:latest"
    ports:
      - ${REDIS_PORT}:${REDIS_PORT}
    env_file:
     - .env
    restart: always
